version: '3.8'

services:
  tumangle-app:
    build: .
    container_name: tumangle-server
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - tumangle_data:/app/data
    restart: unless-stopped

volumes:
  tumangle_data:
